#!/usr/bin/env bash
#install nginx on server listening to 80
apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo "Holberton School for the win!" | sudo tee /var/www/html/index.nginx-debian.html >/dev/null
sudo /etc/init.d/nginx start