#!/usr/bin/env bash
#install load balancer
add-apt-repository -y ppa:vbernat/haproxy-1.5
apt-get -y update
apt-get -y install haproxy=1.5.\*
echo
"frontend front
        bind *:80
        mode http
        default_backend back
backend back
        mode http
        balance roundrobin
        server 810-web-01 34.74.195.119:80 check
        server 810-web-02 104.196.96.41:80 check
        " >> /etc/haproxy/haproxy.cfg
service haproxy restart